package pe.nanamochi.packets;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Packets {

  // Client
  OSU_USER_STATUS(0),
  OSU_MESSAGE(1),
  OSU_EXIT(2),
  OSU_STATUS_UPDATE_REQUEST(3),
  OSU_PONG(4),
  OSU_START_SPECTATING(16),
  OSU_STOP_SPECTATING(17),
  OSU_SPECTATE_FRAMES(18),
  OSU_ERROR_REPORT(20),
  OSU_CANT_SPECTATE(21),
  OSU_PRIVATE_MESSAGE(25),
  OSU_LOBBY_PARTY(29),
  OSU_LOBBY_JOIN(30),
  OSU_MATCH_CREATE(31),
  OSU_MATCH_JOIN(32),
  OSU_MATCH_PARTY(33),
  OSU_MATCH_CHANGE_SLOT(38),
  OSU_MATCH_READY(39),
  OSU_MATCH_LOCK(40),
  OSU_MATCH_CHANGE_SETTINGS(41),
  OSU_MATCH_START(44),

  // Server
  BANCHO_LOGIN_REPLY(5),
  BANCHO_COMMAND_ERROR(6),
  BANCHO_MESSAGE(7),
  BANCHO_PING(8),
  BANCHO_IRC_CHANGE_USERNAME(9),
  BANCHO_IRC_QUIT(10),
  BANCHO_USER_STATS(11),
  BANCHO_USER_QUIT(12),
  BANCHO_SPECTATOR_JOINED(13),
  BANCHO_SPECTATOR_LEFT(14),
  BANCHO_SPECTATE_FRAMES(15),
  BANCHO_VERSION_UPDATE(19),
  BANCHO_SPECTATOR_CANT_SPECTATE(22),
  BANCHO_GET_ATTENTION(23),
  BANCHO_ANNOUNCE(24),
  BANCHO_MATCH_UPDATE(26),
  BANCHO_MATCH_NEW(27),
  BANCHO_MATCH_DISBAND(28),
  BANCHO_LOBBY_JOIN(34),
  BANCHO_LOBBY_PART(35),
  BANCHO_MATCH_JOIN_SUCCESS(36),
  BANCHO_MATCH_JOIN_FAIL(37),
  BANCHO_FELLOW_SPECTATOR_JOINED(42),
  BANCHO_FELLOW_SPECTATOR_LEFT(43),
  BANCHO_MATCH_START(46),

  // Legacy packets
  BANCHO_HANDLE_IRC_JOIN(65535);

  private final int id;

  public static Packets fromId(int id) {
    for (Packets type : values()) {
      if (type.id == id) {
        return type;
      }
    }
    throw new IllegalArgumentException("Unknown packet id: " + id);
  }
}
